export const INTERFACE_TYPE_UNKNOWN = 'INTERFACE_TYPE_UNKNOWN';
export const INTERFACE_TYPE_PLUGIN = 'INTERFACE_TYPE_PLUGIN';
export const INTERFACE_TYPE_PROPERY_INSPECTOR =
  'INTERFACE_TYPE_PROPERY_INSPECTOR';
